### ISSUE TITLE
Progress issues

### ISSUE THREAD

**Issue by ReecaRanse** [Tsume/Maple-Tree#130] opened 2017-10-15 21:47 UTC
Once downloaded and decrypted the Log panel says finished, yet switching to Control Panel you still see the blue progress bar and by checking the folder size of the update you can see its still increasing.

Running 2.1.1.17 On Windows 10.

**Comment by lcsondes** [comment] 2017-10-16 20:42
This could be caused by the changes to Download.cs in 381baa1a4eadfc9ad26f93c0ca0c909151c14633

**Comment by Tsume** [comment] 2017-10-16 21:33
You may be right. That void should be a task and awaited. If it’s too much of an issue. Use .16 until I can get around to fixing it in .17

**Comment by Tsume** [comment] 2017-10-26 21:21
should be fixed

https://github.com/Tsume/Maple-Tree/issues/131

**Closed by Tsume** 2017-10-26 21:21 UTC
