### ISSUE TITLE
Application hangs sometimes when updating game

### ISSUE THREAD

**Issue by darkdrifter** [Tsume/Maple-Tree#5] opened 2017-01-16 13:11 UTC
Everything is in the title, sometimes when updating a game, it just hangs, doing nothing, not utilizing the network or outputting something to the console.

**Comment by Tsume** [comment] 2017-01-16 15:00
I'm not sure what exactly causes this, but I believe I've fixed it for the next build. I'll leave this open for now until it's confirmed.

**Comment by Tsume** [comment] 2017-01-16 15:03
What were you doing when it started to hang?

**Comment by darkdrifter** [comment] 2017-01-16 15:08
I just clicked the "Update" button, and the application didn't do anything other than graying everything.

**Comment by Tsume** [comment] 2017-01-16 18:02
Try this build and let me know if the issue persists.
https://mega.nz/#!I5Vw3TIS!gAalyfPfei_oPW9A9_fNZ8jUq5Aq_t3mOEvkdsztIxA

**Comment by darkdrifter** [comment] 2017-01-16 18:06
It crashes or give null exceptions for everything, I think it's caused because you didn't include the latest .dll with it.

**Comment by Tsume** [comment] 2017-01-16 18:35
Yup, that's exactly why. I keep forgetting to include it.

https://pixxy.in/y1U5171.zip

**Comment by darkdrifter** [comment] 2017-01-16 18:43
Perfect, now it correctly display a 404 when a game isn't found instead of hanging. I think a message box saying that the game wasn't found would be nice.

I got this error when trying to update Mario Maker now:
![image](https://cloud.githubusercontent.com/assets/7112422/21995220/fec8a942-dc23-11e6-8313-562cd4fedd74.png)

**Comment by Maufeat** [comment] 2017-01-16 19:51
I think the servers are offline? Can't connect to the chat and can't update/download games.

**Comment by Tsume** [comment] 2017-01-16 19:55
They're offline at the moment. mapletree.tsumes.com is up for testing, if you'd like to use it, but network based features may not work until you have the updated client, which you can compile from the source if you're hip. I might upload a pre-release later today, since cemu 1.7.0 is public.

**Comment by Tsume** [comment] 2017-01-16 19:56
That error should be fixed in the latest commit darkdrifter

**Closed** 2017-01-17 02:49 UTC
Labels: bug
